### ISSUE TITLE
How to store form data after HttpPost

### ISSUE THREAD

**Issue by Franklin89** [ajamaeen/asp.net-mvc-wizard#1]
First off great blog post and tutorial. I followed this and implemented it in a bit a different way. But I was wondering how do you store your state of the data for each step?

In the examples on the HttpGet methods you always create a new instance of the ViewModel for the step. Do you have a way that on NextCommand the data gets stored along side with the wizard state and then gets loaded again if the user returns to that step in the wizard?

**Comment by ajamaeen** [comment]
Thanks ,
On **OnExecute** action for command i do save the navigator state  **Navigator.SaveWizardState();**

WizardState : contains all wizard steps with active steps Id , when user navigate i do serialize the wizard state to JSON and save it in database for logged in user using **NavigatorPersistenceService** 
then load the state each time page loaded .

Check the [NavigatorPersistenceService](https://github.com/ajamaeen/asp.net-mvc-wizard/blob/master/Wizard.Web/Services/NavigatorPersistenceService.cs)

[Wizard State](https://github.com/ajamaeen/asp.net-mvc-wizard/blob/master/Wizard.Component/WizardState.cs)

**Comment by Franklin89** [comment]
thanks for getting back to me

I see that...but that is just the WizardState and not the data that the user input? or can I add that somehow?

**Comment by ajamaeen** [comment]
Saving user input is not wizard problem.
As u did in normal controller/action load data from your data store in get method and save it. On post method.

Create ur own seevice to save and load.



Best regards

________________________________

**Comment by Franklin89** [comment]
ah i see...
thanks for clarifying...
